apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-test
spec:
  selector:
    matchLabels:
      app: service-test
  template:
    metadata:
      labels:
        app: service-test
    spec:
      containers:
        - name: service-test
          image: service2
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "8080"
          resources:
            limits:
              memory: "64Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
              name: http

---
apiVersion: v1
kind: Service
metadata:
  name: service-test
spec:
  selector:
    app: service-test
  ports:
    - port: 80
      targetPort: http
